# Generated by Django 5.2.1 on 2025-05-25 19:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DollarSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('Basic', 'Basic - Daily Plan'), ('Platinum', 'Platinum - Monthly Plan'), ('Bronze', 'Bronze - Quarterly Plan'), ('Silver', 'Silver - Biannual Plan'), ('Gold', 'Gold - Annual Plan')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='NairaSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('Basic', 'Basic - Daily Plan'), ('Platinum', 'Platinum - Monthly Plan'), ('Bronze', 'Bronze - Quarterly Plan'), ('Silver', 'Silver - Biannual Plan'), ('Gold', 'Gold - Annual Plan'), ('ForeignBasic', 'Basic - Daily Plan'), ('ForeignPlatinum', 'Platinum - Monthly Plan'), ('ForeignBronze', 'Bronze - Quarterly Plan'), ('ForeignSilver', 'Silver - Biannual Plan'), ('ForeignGold', 'Gold - Annual Plan')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, max_length=200, null=True)),
                ('datenow', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('dollar_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.dollarsubscriptionplan')),
                ('naira_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.nairasubscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
