# Generated by Django 4.2.5 on 2023-10-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_dollarsubscriptionplan_nairasubscriptionplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ref_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
