# Generated by Django 4.2.5 on 2023-10-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_nairasubscriptionplan_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paystack_due_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paystack_sub_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
