# Generated by Django 4.2.5 on 2023-10-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscription_paystack_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nairasubscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('Basic', 'Basic_Daily_Plan'), ('Platinum', 'Platinum_Monthly_Plan'), ('Bronze', 'Bronze_Quarterly_Plan'), ('Silver', 'Silver_Biannual_Plan'), ('Gold', 'Gold - Annual_Plan')], max_length=20),
        ),
    ]
