# Generated by Django 4.2.5 on 2023-10-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_alter_nairasubscriptionplan_plan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='paystack_due_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='paystack_sub_date',
        ),
    ]
