# Generated by Django 4.2.5 on 2023-10-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_remove_subscription_paystack_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollarsubscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('Platinum', 'Platinum_Monthly_Plan'), ('Bronze', 'Bronze_Quarterly_Plan'), ('Silver', 'Silver_Biannual_Plan'), ('Gold', 'Gold_Annual_Plan')], max_length=20),
        ),
    ]
