# Generated by Django 4.2.5 on 2023-10-26 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_alter_dollarsubscriptionplan_plan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='datenow',
            field=models.DateField(default=datetime.datetime(2023, 10, 26, 8, 48, 54, 370588)),
        ),
    ]
