# Generated by Django 4.2.5 on 2023-10-26 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_subscription_datenow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='datenow',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 10, 26, 8, 49, 23, 76307), null=True),
        ),
    ]
