# Generated by Django 4.2.5 on 2023-10-26 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_alter_subscription_datenow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='datenow',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
