# Generated by Django 4.2.5 on 2023-10-26 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0014_alter_subscription_datenow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='datenow',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 26, 8, 54, 7, 172318), null=True),
        ),
    ]
