# Generated by Django 4.2.5 on 2023-10-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0016_alter_subscription_datenow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollarsubscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('Basic', 'Basic - Daily Plan'), ('Platinum', 'Platinum - Monthly Plan'), ('Bronze', 'Bronze - Quarterly Plan'), ('Silver', 'Silver - Biannual Plan'), ('Gold', 'Gold - Annual Plan')], max_length=20),
        ),
    ]
