# Generated by Django 4.2.5 on 2023-12-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0018_alter_dollarsubscriptionplan_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollarsubscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('Basic', 'Basic - Daily Plan'), ('Platinum', 'Platinum - Monthly Plan'), ('Bronze', 'Bronze - Quarterly Plan'), ('Silver', 'Silver - Biannual Plan'), ('Gold', 'Gold - Annual Plan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nairasubscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('Basic', 'Basic - Daily Plan'), ('Platinum', 'Platinum - Monthly Plan'), ('Bronze', 'Bronze - Quarterly Plan'), ('Silver', 'Silver - Biannual Plan'), ('Gold', 'Gold - Annual Plan'), ('ForeignBasic', 'Basic - Daily Plan'), ('ForeignPlatinum', 'Platinum - Monthly Plan'), ('ForeignBronze', 'Bronze - Quarterly Plan'), ('ForeignSilver', 'Silver - Biannual Plan'), ('ForeignGold', 'Gold - Annual Plan')], max_length=20),
        ),
    ]
