# Generated by Django 5.2.1 on 2025-05-25 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('itemcategory', models.CharField(blank=True, max_length=200, null=True)),
                ('itemname', models.CharField(blank=True, max_length=200, null=True)),
                ('itemimage', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('itemimage2', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('itemimage3', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('itemvideo', models.FileField(blank=True, null=True, upload_to='media/')),
                ('itemprice', models.FloatField(blank=True, null=True)),
                ('itemdiscount', models.FloatField(blank=True, default=0, null=True)),
                ('itemamount', models.FloatField(blank=True, null=True)),
                ('itemsize', models.CharField(blank=True, max_length=200, null=True)),
                ('itemcolors', models.CharField(blank=True, max_length=100, null=True)),
                ('itemdescription', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('purchaser', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_purchased', models.BooleanField(blank=True, default=False, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cart_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.product')),
            ],
        ),
    ]
