# Generated by Django 4.2.5 on 2023-10-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='itemimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
