# Generated by Django 4.2.5 on 2023-10-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_product_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='itemimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
