# Generated by Django 4.2.5 on 2023-10-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_alter_product_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='itempercentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
