# Generated by Django 4.2.5 on 2023-10-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_product_itempercentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='itempercentage',
        ),
    ]
