# Generated by Django 4.2.5 on 2023-10-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_remove_product_itempercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='itemdiscount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
