# Generated by Django 4.2.5 on 2023-12-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_alter_product_itemdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='itemimage2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='product',
            name='itemimage3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='itemcolors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
