# Generated by Django 4.2.5 on 2023-12-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_product_itemimage2_product_itemimage3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='itemvideo',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
