# Generated by Django 4.2.6 on 2024-01-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_product_itemvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='itemamount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='itemdiscount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='itemprice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
