# Generated by Django 4.2.5 on 2023-10-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_address_user_businessname_user_businesstype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='businessname',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
