# Generated by Django 4.2.5 on 2025-04-26 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 26, 7, 58, 0, 604525)),
        ),
        migrations.AlterField(
            model_name='user',
            name='idpic',
            field=models.ImageField(blank=True, null=True, upload_to='id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='profilepic'),
        ),
    ]
