# Generated by Django 5.2.1 on 2025-05-25 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_user_date_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 25, 21, 10, 33, 65928)),
        ),
    ]
