# Generated by Django 4.2.5 on 2023-10-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, default='avatar.svg', upload_to=''),
        ),
    ]
