# Generated by Django 5.2.1 on 2025-05-25 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_date_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passwordresetcode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='securityanswer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='securityquestion',
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 25, 21, 22, 33, 361301)),
        ),
    ]
