# Generated by Django 5.2.1 on 2025-05-25 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_user_facebook_remove_user_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passwordresetphone',
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 25, 21, 30, 4, 984033)),
        ),
    ]
