# Generated by Django 5.2.1 on 2025-05-25 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_user_passwordresetphone_alter_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='record',
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 25, 22, 10, 11, 489726)),
        ),
    ]
