# Generated by Django 4.2.5 on 2023-10-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_user_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(default='icons/icon.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, default='icons/avatar.png', upload_to=''),
        ),
    ]
