# Generated by Django 4.2.5 on 2023-10-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_user_logo_alter_user_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordresetcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
