# Generated by Django 4.2.5 on 2023-10-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_user_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='securityanswer',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='securityquestion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
