# Generated by Django 4.2.5 on 2023-10-23 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_user_trial_end_user_trial_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='paid',
            new_name='subscribed',
        ),
    ]
