# Generated by Django 4.2.5 on 2023-10-24 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_paid_user_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 7, 33, 45, 994391)),
        ),
    ]
