# Generated by Django 4.2.5 on 2023-10-25 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_user_date_alter_user_securityanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 23, 59, 7, 530383)),
        ),
    ]
