# Generated by Django 4.2.5 on 2023-10-26 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 8, 52, 35, 391831)),
        ),
    ]
