# Generated by Django 4.2.5 on 2023-10-28 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 7, 30, 56, 163156)),
        ),
        migrations.AlterField(
            model_name='user',
            name='securityanswer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
