# Generated by Django 4.2.5 on 2023-10-28 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_alter_user_date_alter_user_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordresetphone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 19, 59, 53, 628238)),
        ),
    ]
