# Generated by Django 4.2.5 on 2023-10-30 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_user_passwordresetphone_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 1, 46, 50, 684076)),
        ),
    ]
