# Generated by Django 4.2.5 on 2023-12-06 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_remove_user_dob_remove_user_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 10, 11, 45, 616406)),
        ),
    ]
