# Generated by Django 4.2.5 on 2023-12-17 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_user_coins_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 21, 7, 44, 935993)),
        ),
    ]
