# Generated by Django 4.2.6 on 2024-04-29 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_user_idnumber_user_idpic_user_meansofid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 29, 15, 39, 16, 775288)),
        ),
    ]
