# Generated by Django 4.2.6 on 2024-05-01 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_alter_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='businesstype',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shopcategory',
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 1, 12, 1, 15, 76460)),
        ),
    ]
