# Generated by Django 4.2.6 on 2024-05-09 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_alter_user_date_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 22, 28, 7, 970223)),
        ),
    ]
