# Generated by Django 4.2.6 on 2024-05-10 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 7, 40, 17, 404786)),
        ),
    ]
