# Generated by Django 4.2.6 on 2024-09-19 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_alter_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='record',
            field=models.FileField(blank=True, null=True, upload_to='records/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 9, 0, 17, 670598)),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
