# Generated by Django 4.2.6 on 2024-09-19 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_user_record_alter_user_date_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 19, 10, 11, 38, 370391)),
        ),
    ]
