# Generated by Django 4.2.6 on 2024-05-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_receivedchats_sentchats_delete_userchats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceivedChats',
        ),
    ]
